// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the setProject command in the CLI.
// For example: `firebase-studio setProject <project-id>`

// For more information, see the Firebase Studio documentation.
// https://firebase.google.com/docs/studio

// Your web app's Firebase configuration
export const firebaseConfig = {
  "projectId": "studio-9465853285-42575",
  "appId": "1:309899986959:web:5c6bc92750440a7eb57b7a",
  "apiKey": "AIzaSyCv2r4VZDnolxFWTzvOCxmf9UR1Fzt0Cws",
  "authDomain": "studio-9465853285-42575.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "309899986959"
};
