// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, use the setProject command in the CLI.
// For example: `firebase-studio setProject <project-id>`

// For more information, see the Firebase Studio documentation.
// https://firebase.google.com/docs/studio

// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: "TODO: Your API Key",
  authDomain: "TODO: Your auth domain",
  projectId: "TODO: Your project ID",
  storageBucket: "TODO: Your storage bucket",
  messagingSenderId: "TODO: Your messaging sender ID",
  appId: "TODO: Your app ID"
};
